spring.application.name=reactive-orders
spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/reactive_orders_db?authSource=admin
server.port=8080
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
