"""
02_orchestrator_agent.py
==================================================================
Phase 5 — Orchestrators (Multi-Agent)
The OrchestratorAgent: plan -> execute (dependency-aware) -> synthesize -> run.

JAVA ANALOGY
------------
The OrchestratorAgent is a *Saga orchestrator*. It does no domain work itself;
it holds a registry of specialist workers (a Map<String, Worker>), asks an LLM
to PLAN the sequence of subtasks at runtime, EXECUTES them in dependency order
passing each step's output forward as context, then SYNTHESIZES the results
into one final answer. Compare to:

    @Service class BlogSaga {
        Map<String, Worker> workers;          // injected strategy beans
        List<Step> plan(String goal);          // here: an LLM writes the plan
        Map<Integer,String> execute(plan);     // ordered service calls
        String synthesize(goal, results);      // assemble the response
    }

The new-and-dangerous part: the PLAN is generated by a non-deterministic LLM,
so we parse its JSON DEFENSIVELY (strip markdown fences, try/except with a
single-step fallback) — exactly like guarding an objectMapper.readValue() on an
untrusted downstream response.

OFFLINE MODE
------------
`USE_MOCK = True` makes this run with NO API key. The fake planner returns a
VALID JSON plan (Researcher -> Writer -> Editor with real depends_on edges) so
that `execute` and `synthesize` genuinely exercise dependency passing, and the
fake workers return deterministic text. Flip the flag (and set
ANTHROPIC_API_KEY) for the real model. See `_build_llm()`.

This file is SELF-CONTAINED: it includes its own copy of WorkerAgent and the
fake model so it runs standalone. (It also tries to import from
`01_worker_agent.py` first if you've placed them on the path; see
`_load_worker_class()`.)

Run:
    python 02_orchestrator_agent.py
==================================================================
"""

from __future__ import annotations

import json
import logging
import re
from typing import Protocol

from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage

# ─────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────
# Set to False (and export ANTHROPIC_API_KEY) to call the real model.
USE_MOCK: bool = True

# Model id used ONLY when USE_MOCK is False.
REAL_MODEL_ID: str = "claude-sonnet-4-6"

# Bulkhead: cap how many steps a plan may contain, so a runaway LLM can't fan
# out into unbounded API calls (see notes.md "unbounded fan-out cost").
MAX_PLAN_STEPS: int = 10

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-7s | %(name)s | %(message)s",
)
logger = logging.getLogger("orchestrator")


# ─────────────────────────────────────────────────────────────────
# Structural types (interface both real + fake models satisfy)
# ─────────────────────────────────────────────────────────────────
class AIResponseLike(Protocol):
    content: str


class ChatLike(Protocol):
    def invoke(self, messages: list[BaseMessage]) -> AIResponseLike: ...


# ─────────────────────────────────────────────────────────────────
# Deterministic offline fakes (worker model + planner/synthesizer model)
# ─────────────────────────────────────────────────────────────────
class _FakeResponse:
    def __init__(self, content: str) -> None:
        self.content = content


class FakeWorkerModel:
    """Deterministic stand-in for a worker's ChatAnthropic.

    Picks canned output by inspecting the worker's system prompt, and echoes
    whether it received upstream context so you can SEE the dependency edges.
    """

    def invoke(self, messages: list[BaseMessage]) -> _FakeResponse:
        system = next(
            (m.content for m in messages if isinstance(m, SystemMessage)), ""
        ).lower()
        humans = [m.content for m in messages if isinstance(m, HumanMessage)]
        task = (humans[-1] if humans else "").replace("Task:\n", "").strip()
        context = humans[0] if len(humans) > 1 else ""
        had_ctx = "yes" if context.strip() else "no"
        snippet = task[:60]

        # IMPORTANT: check "edit"/"writ" BEFORE "research". The Writer/Editor
        # system prompts contain the word "research" incidentally ("...based on
        # provided research."), so a naive "research"-first check would misroute
        # them. Order matters — same care you'd take with overlapping route
        # patterns in a Spring @RequestMapping.
        if "edit" in system:
            return _FakeResponse(
                "EDITED POST:\n"
                "Retrieval-Augmented Generation (RAG) grounds enterprise AI in "
                "your own documents, reducing hallucination and honoring data "
                "governance — no retraining required.\n"
                f"(mock edit; task={snippet!r}; received_context={had_ctx})"
            )
        return _FakeResponse(
            f"GENERIC OUTPUT; task={snippet!r}; received_context={had_ctx}"
        )


class FakeOrchestratorModel:
    """Deterministic stand-in for the orchestrator's ChatAnthropic.

    Two responsibilities, detected from the prompt text:
      * PLAN  -> returns a VALID JSON array with real depends_on edges, wrapped
                 in a ```json fence on purpose so the fence-stripping guard is
                 exercised end to end.
      * SYNTH -> returns a deterministic merged answer.
    """

    def invoke(self, messages: list[BaseMessage]) -> _FakeResponse:
        prompt = messages[-1].content if messages else ""

        if "Return ONLY valid JSON" in prompt or "subtasks" in prompt:
            # NOTE: wrapped in a markdown fence to PROVE the re.sub strip works.
            plan_json = [
                {
                    "step": 1,
                    "worker": "Researcher",
                    "task": "Gather 3 enterprise benefits of RAG with sources.",
                    "depends_on": [],
                },
                {
                    "step": 2,
                    "worker": "Writer",
                    "task": "Write a 300-word blog post using the research.",
                    "depends_on": [1],
                },
                {
                    "step": 3,
                    "worker": "Editor",
                    "task": "Edit the draft for clarity, grammar, and flow.",
                    "depends_on": [2],
                },
            ]
            return _FakeResponse("```json\n" + json.dumps(plan_json) + "\n```")

        # Otherwise this is a synthesis request.
        return _FakeResponse(
            "FINAL BLOG POST (synthesized):\n"
            "Retrieval-Augmented Generation (RAG) grounds enterprise AI in your "
            "own documents — reducing hallucination, honoring data governance, "
            "and avoiding costly retraining. Researched, drafted, and edited by "
            "a coordinated worker pipeline.\n"
            "(mock synthesis combining steps 1-3)"
        )


def _build_llm(*, for_orchestrator: bool, role_hint: str = "generic") -> ChatLike:
    """Factory: fake model offline, real ChatAnthropic when USE_MOCK is False.

    To use the REAL model: set USE_MOCK = False and export ANTHROPIC_API_KEY.
    The langchain_anthropic import is lazy so this file runs with NO real
    dependency in mock mode.
    """
    if USE_MOCK:
        kind = "Orchestrator" if for_orchestrator else f"Worker({role_hint})"
        logger.info("USE_MOCK=True -> Fake%sModel", kind)
        return FakeOrchestratorModel() if for_orchestrator else FakeWorkerModel()

    # ── Real model path (requires `pip install langchain-anthropic`) ──
    from langchain_anthropic import ChatAnthropic  # noqa: PLC0415

    logger.info("USE_MOCK=False -> ChatAnthropic(model=%s)", REAL_MODEL_ID)
    return ChatAnthropic(model=REAL_MODEL_ID)  # type: ignore[return-value]


# ─────────────────────────────────────────────────────────────────
# WorkerAgent — self-contained copy (mirrors 01_worker_agent.py)
# ─────────────────────────────────────────────────────────────────
class WorkerAgent:
    """A single-specialty agent; behaviour injected via `instructions`.

    Java analogy: a concrete strategy bean. Stateless across calls.
    """

    def __init__(self, name: str, specialty: str, instructions: str = "") -> None:
        self.name: str = name
        self.specialty: str = specialty
        self.instructions: str = instructions or f"You are a {specialty} specialist."
        self.llm: ChatLike = _build_llm(for_orchestrator=False, role_hint=specialty)

    def run(self, task: str, context: str = "") -> str:
        """Execute one subtask. `context` carries upstream dependency outputs."""
        messages: list[BaseMessage] = [SystemMessage(content=self.instructions)]
        if context:
            messages.append(HumanMessage(content=f"Context:\n{context}"))
        messages.append(HumanMessage(content=f"Task:\n{task}"))
        try:
            response = self.llm.invoke(messages)
            logger.info("  [%s] completed task", self.name)
            return response.content
        except Exception as exc:  # noqa: BLE001
            logger.error("  [%s] failed: %s", self.name, exc)
            return f"Error: worker '{self.name}' failed: {exc}"


def _load_worker_class() -> type[WorkerAgent]:
    """Prefer the WorkerAgent from 01_worker_agent.py if importable.

    Because `01_worker_agent.py` starts with a digit it is not a valid module
    name for a plain `import`, so we load it via importlib if present. If that
    fails (file moved/renamed), we fall back to the self-contained copy above.
    """
    import importlib.util  # noqa: PLC0415
    import pathlib  # noqa: PLC0415

    candidate = pathlib.Path(__file__).with_name("01_worker_agent.py")
    if not candidate.exists():
        logger.info("01_worker_agent.py not found -> using self-contained WorkerAgent")
        return WorkerAgent
    try:
        spec = importlib.util.spec_from_file_location("worker_mod", candidate)
        if spec is None or spec.loader is None:
            return WorkerAgent
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        logger.info("Imported WorkerAgent from 01_worker_agent.py")
        # NOTE: keep our local USE_MOCK authoritative; the imported class uses
        # its own flag, so for a single source of truth we use the local copy.
        return WorkerAgent  # local copy honors THIS file's USE_MOCK / MAX_PLAN_STEPS
    except Exception as exc:  # noqa: BLE001
        logger.warning("Could not import 01_worker_agent.py (%s); using local copy", exc)
        return WorkerAgent


# ─────────────────────────────────────────────────────────────────
# OrchestratorAgent — the Saga coordinator
# ─────────────────────────────────────────────────────────────────
class OrchestratorAgent:
    """Decompose a goal -> delegate to workers -> synthesize one answer."""

    def __init__(self, workers: list[WorkerAgent]) -> None:
        # Registry keyed by name == Map<String, Worker> of strategy beans.
        self.workers: dict[str, WorkerAgent] = {w.name: w for w in workers}
        self.llm: ChatLike = _build_llm(for_orchestrator=True)

    # ── Phase 1: PLAN (the LLM acts as a workflow designer) ──
    def plan(self, goal: str) -> list[dict]:
        plan_prompt = f"""
Break down this goal into ordered subtasks. Assign each to the best available worker.
Available workers: {list(self.workers.keys())}
Goal: {goal}

Return ONLY valid JSON array (no markdown):
[
  {{"step": 1, "worker": "WorkerName", "task": "specific instruction", "depends_on": []}},
  {{"step": 2, "worker": "WorkerName", "task": "specific instruction", "depends_on": [1]}}
]"""
        response = self.llm.invoke([HumanMessage(content=plan_prompt)])

        # DEFENSIVE PARSING — the model output is untrusted.
        # 1) strip common ```json ... ``` markdown fences
        json_text = re.sub(r"```json|```", "", response.content).strip()
        try:
            parsed = json.loads(json_text)
            if not isinstance(parsed, list) or not parsed:
                raise ValueError("plan is not a non-empty JSON array")
        except (json.JSONDecodeError, ValueError) as exc:
            # 2) graceful fallback: a single step handing the whole goal to the
            #    first worker (system degrades, never crashes).
            logger.warning("Plan parse failed (%s); falling back to single step", exc)
            first = next(iter(self.workers), "Worker")
            return [{"step": 1, "worker": first, "task": goal, "depends_on": []}]

        # 3) bulkhead: cap fan-out
        if len(parsed) > MAX_PLAN_STEPS:
            logger.warning(
                "Plan has %d steps > MAX_PLAN_STEPS=%d; truncating",
                len(parsed),
                MAX_PLAN_STEPS,
            )
            parsed = parsed[:MAX_PLAN_STEPS]
        return parsed

    # ── Phase 2: EXECUTE (dependency-aware delegation) ──
    def execute(self, plan: list[dict]) -> dict[int, str]:
        results: dict[int, str] = {}
        # Sort by step number: for a monotonic plan this is a valid topological
        # order (a real DAG executor would topo-sort + reject cycles — exercise 4).
        for step in sorted(plan, key=lambda s: s.get("step", 0)):
            step_num = step.get("step")
            worker_name = step.get("worker")
            task = step.get("task", "")

            # Gather and forward the outputs of every dependency as context.
            dep_context = "\n\n".join(
                f"Step {d} result:\n{results[d]}"
                for d in step.get("depends_on", [])
                if d in results
            )

            if worker_name in self.workers:
                logger.info(
                    "Step %s -> %s (deps=%s)",
                    step_num,
                    worker_name,
                    step.get("depends_on", []),
                )
                results[step_num] = self.workers[worker_name].run(task, dep_context)
            else:
                # Guard: LLM may name a worker that doesn't exist (no KeyError).
                logger.error("Step %s names unknown worker %r", step_num, worker_name)
                results[step_num] = f"Error: worker '{worker_name}' not found"

        return results

    # ── Phase 3: SYNTHESIZE (the reduce step) ──
    def synthesize(self, goal: str, step_results: dict[int, str]) -> str:
        synthesis_prompt = f"""
Original goal: {goal}

Worker outputs:
{json.dumps(step_results, indent=2)}

Synthesize these into a final comprehensive response."""
        return self.llm.invoke([HumanMessage(content=synthesis_prompt)]).content

    # ── Public entry point: ties the three phases together ──
    def run(self, goal: str) -> str:
        print(f"\nGoal: {goal}")
        plan = self.plan(goal)
        print(f"Plan: {len(plan)} steps")
        for s in sorted(plan, key=lambda x: x.get("step", 0)):
            print(
                f"  step {s.get('step')}: {s.get('worker')} "
                f"(depends_on={s.get('depends_on', [])}) -> {s.get('task', '')[:50]}"
            )
        results = self.execute(plan)
        return self.synthesize(goal, results)


def build_default_workers(worker_cls: type[WorkerAgent]) -> list[WorkerAgent]:
    """The Researcher -> Writer -> Editor blog crew."""
    return [
        worker_cls(
            "Researcher", "research", "Find facts and data. Be specific and cite sources."
        ),
        worker_cls(
            "Writer", "writing", "Write clear, engaging content based on provided research."
        ),
        worker_cls(
            "Editor", "editing", "Review content for clarity, grammar, and logical flow."
        ),
    ]


# ─────────────────────────────────────────────────────────────────
# Demo — the full blog-post orchestration, end to end
# ─────────────────────────────────────────────────────────────────
def _demo() -> None:
    print("=" * 64)
    print(f"OrchestratorAgent demo  (USE_MOCK={USE_MOCK})")
    print("=" * 64)

    worker_cls = _load_worker_class()
    orchestrator = OrchestratorAgent(build_default_workers(worker_cls))

    final = orchestrator.run(
        "Write a 300-word blog post about the benefits of RAG in enterprise AI"
    )

    print("\n" + "=" * 64)
    print("FINAL OUTPUT")
    print("=" * 64)
    print(final)


if __name__ == "__main__":
    _demo()
